services:
    web:
        container_name: kazeem-app
        image: ghcr.io/luthfi9251/kazeem-app:latest
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 3000:3000
        env_file:
            - .env
        environment:
            - DATABASE_URL=mysql://root:B4rc3lon4@host.docker.internal:3306/kazeemdb?schema=public
