/**
 *  aturan penamaan
 *  KESANTRIAN_KELOLA_SANTRI
 *  [SCOPE]_[PAGE_NAME]*
 *  */

const PAGE_NAME = {
    USER_HOME: "USER_HOME",
    USER_GROUP_HOME: "USER_GROUP_HOME",
    KESANTRIAN_KELOLA_SANTRI: "KESANTRIAN_KELOLA_SANTRI",
    KESANTRIAN_WALI_SANTRI: "KESANTRIAN_WALI_SANTRI",
    KESANTRIAN_KESEHATAN: "KESANTRIAN_KESEHATAN",
    KESANTRIAN_PELANGGARAN: "KESANTRIAN_PELANGGARAN",
    KESANTRIAN_KATEGORI_PELANGGARAN: "KESANTRIAN_KATEGORI_PELANGGARAN",
    KESANTRIAN_KAMAR_SANTRI: "KESANTRIAN_KAMAR",
    KESANTRIAN_HAFALAN_SANTRI: "KESANTRIAN_HAFALAN_SANTRI",
    KEMADRASAHAN_KELOLA_KELAS: "KEMADRASAHAN_KELOLA_KELAS",
    KEMADRASAHAN_TAHUN_AJAR: "KEMADRASAHAN_TAHUN_AJAR",
    KEPEGAWAIAN_KELOLA_PEGAWAI: "KEPEGAWAIAN_KELOLA_PEGAWAI",
    KEPEGAWAIAN_JABATAN_PEGAWAI: "KEPEGAWAIAN_JABATAN_PEGAWAI",
    KEPEGAWAIAN_PRESENSI: "KEPEGAWAIAN_PRESENSI",
    SETTING_AKUN_USER: "SETTING_AKUN_USER",
    SETTING_KEPONDOKAN: "SETTING_KEPONDOKAN",
    SETTING_WHATSAPP_API: "SETTING_WHATSAPP_API",
};

module.exports = {
    PAGE_NAME,
};
