const PAGE_NAME = {
    USER_HOME: "USER_HOME",
    USER_GROUP_HOME: "USER_GROUP_HOME",
    KESANTRIAN_KELOLA_SANTRI: "KESANTRIAN_KELOLA_SANTRI",
    KESANTRIAN_WALI_SANTRI: "KESANTRIAN_WALI_SANTRI",
    KESANTRIAN_KESEHATAN: "KESANTRIAN_KESEHATAN",
    KESANTRIAN_PELANGGARAN: "KESANTRIAN_PELANGGARAN",
    KESANTRIAN_KATEGORI_PELANGGARAN: "KESANTRIAN_KATEGORI_PELANGGARAN",
    KEMADRASAHAN_KELOLA_KELAS: "KEMADRASAHAN_KELOLA_KELAS",
    KEMADRASAHAN_TAHUN_AJAR: "KEMADRASAHAN_TAHUN_AJAR",
};

module.exports = {
    PAGE_NAME,
};
