export const PAGE_NAME = {
    MANAGE_USER_PAGE: "MANAGE_USER_PAGE",
    MANAGE_ROLE_PAGE: "MANAGE_ROLE_PAGE",
    MANAGE_SANTRI_PAGE: "MANAGE_SANTRI_PAGE",
    MANAGE_PELANGGARAN_PAGE: "MANAGE_PELANGGARAN_PAGE",
    MANAGE_MADRASAH_PAGE: "MANAGE_MADRASAH_PAGE",
    MANAGE_KAMAR_PAGE: "MANAGE_KAMAR_PAGE",
    MANAGE_HAFALAN_PAGE: "MANAGE_HAFALAN_PAGE",
};
